### ISSUE TITLE
4s 7.1系统出现崩溃

### ISSUE THREAD

**Issue by muermaru** [youngsoft/YSTextInputKeyboardCategory#1]
![b7e170ca-f50e-4625-9317-df10b0c6e2d6](https://cloud.githubusercontent.com/assets/12495960/14343655/ff4252d0-fcd4-11e5-8980-73761580e709.png)
![de24cf7f-b72e-4e9b-a0f5-9005fe0246b2](https://cloud.githubusercontent.com/assets/12495960/14343657/001e1d60-fcd5-11e5-9adf-8b94607eb90f.png)

如图，xcode和错误日志的记录

我的textfield是放在tableview上的，其中一个cell点击会进入多层tableview，崩溃是出现在最后一层的cell选中后。textfield的kbMovingView一开始我设置的是self.view，后面尝试换成tableview也是一样的情况

我是能否帮忙查看一下是什么问题？

**Comment by muermaru** [comment]
看了一下，这个问题不是在外面的textfield触发的，而是由于tableview的tableHeaderView上加的一个searchbar导致的，但是我调整了searchbar的kbMovingView属性也是同样的问题，还是需要麻烦作者有空看一下

**Comment by youngsoft** [comment]
非常感谢，原因是对UISearchbar的支持导致的，我把对UISearchBar的支持取消了。。 非常感谢你的问题。。。

**Comment by muermaru** [comment]
好的，不过这个问题似乎只在我的4s的7.1系统测试机上出现，不知道具体是机型还是系统版本的问题，所以我目前也是暂时屏蔽了在8以下系统显示searchbar，不过还希望作者有空能解决这个问题支持低版本或者机型

**Comment by zhaokaihan** [comment]
这个问题我也发现了，在iOS8.2系统的手机上也会出现闪退，同样是tableview顶部是searchbar

**Comment by zhaokaihan** [comment]
线上版本客户反馈闪退，呜呜，好伤心

**Comment by youngsoft** [comment]
你下载最新的版本吧。不要用你老版本了。新版本已经取消了对UISearchBar的支持了，对UISearchBar的支持有可能会导致崩溃！！！！

**Comment by zhaokaihan** [comment]
已经替换，想问下这个问题是searchbar的什么导致的，会影响到哪些版本的用户，以便决定是否更新线上版本。谢谢
